# permissions for end users to view mariadbbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mariadbbackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mariadb-operator
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mariadbbackup-viewer-role
rules:
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbbackups/status
  verbs:
  - get
