---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - jobs
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbbackups/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbs/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.xyzcompany.com
  resources:
  - mariadbs/status
  verbs:
  - get
  - patch
  - update
