## Append samples you want in your CSV to this file as resources ##
resources:
- mariadb_v1alpha1_mariadb.yaml
- mariadb_v1alpha1_mariadbbackup.yaml
- mariadb_v1alpha1_mariadbmonitor.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
