apiVersion: mariadb.xyzcompany.com/v1alpha1
kind: MariaDBMonitor
metadata:
  labels:
    app.kubernetes.io/name: mariadbmonitor
    app.kubernetes.io/instance: mariadbmonitor-sample
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mariadb-operator
  name: mariadbmonitor-sample
spec:
  # TODO(user): Add fields here
  size: 1

  # Database source to connect with for colleting metrics

  # Format: "<db-user>:<db-password>@(<dbhost>:<dbport>)/<dbname>">

  # Make approprite changes

  dataSourceName: "root:password@(192.168.49.2:30685)/test-db"

  # Image name with version

  # Refer https://registry.hub.docker.com/r/prom/mysqld-exporter for more details

  image: "prom/mysqld-exporter"
