apiVersion: mariadb.xyzcompany.com/v1alpha1
kind: MariaDBBackup
metadata:
  labels:
    app.kubernetes.io/name: mariadbbackup
    app.kubernetes.io/instance: mariadbbackup-sample
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mariadb-operator
  name: mariadbbackup-sample
spec:
  # Backup Path
  backupPath: "/mnt/backup"

  # Backup Size (Ex. 1Gi, 100Mi)
  backupSize: "1Gi" 

  # Schedule period for the CronJob.
  # This spec allow you setup the backup frequency
  # Default: "0 0 * * *" # daily at 00:00
  schedule: "* * * * 1-5"
 

